# Generated by Django 4.2 on 2023-04-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boysdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('from_city', models.CharField(max_length=15)),
                ('living_purpose', models.CharField(max_length=15)),
                ('occupation', models.CharField(max_length=10)),
                ('starting_date', models.DateField()),
                ('sharig_required', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=10)),
                ('monday', models.CharField(max_length=10)),
                ('tuesday', models.CharField(max_length=10)),
                ('wednesday', models.CharField(max_length=10)),
                ('thursday', models.CharField(max_length=10)),
                ('friday', models.CharField(max_length=10)),
                ('saturaday', models.CharField(max_length=10)),
                ('sunday', models.CharField(max_length=10)),
            ],
        ),
    ]
