# Generated by Django 4.2 on 2023-04-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempapp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shivaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=20)),
            ],
        ),
    ]
