# Generated by Django 4.2 on 2023-04-28 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempapp2', '0002_shivaya'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shivaya',
        ),
    ]
