# Generated by Django 4.2 on 2023-04-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempapp2', '0003_delete_shivaya'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostelboysdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('block', models.CharField(max_length=5)),
                ('share_members', models.IntegerField()),
                ('room_no', models.IntegerField()),
                ('joining_date', models.DateField()),
                ('rent', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
